config/routes.rb
Rails.application.routes.draw do
  
  resources :exam_evaluations
  devise_for :logins
  
  get 'dashboard/home'

  resources :admins do
    collection do
      get 'home'
    end
  end

  resources :schools do
    resources :batches do
      member do
        get 'add_courses'
        patch 'create_courses'
      end

      resources :enrollments do
        member do
          post 'enrollment_verdict'
        end
      end
    end
    resources :courses
    resources :students do
      member do
        get 'enrollments'
        post 'request_enrollment'
        get 'classmates'
      end

      resources :progress_cards
    end
  end

  
  root "dashboard#home"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  #This is root action
  #If any user (super_admin, school_admin, student) signs in, it lands to this page.
  def home
      @school = current_login.loginable.school
      @student = current_login.loginable if current_login.student?
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/home.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <h1>Welcome To Test LMS System</h1>
  </div>
  <div class="row">
    <div class="col-sm-3">
    <% if current_login.admin? %>
      <% if current_login.loginable.school_admin? %>
        <p><%= link_to 'Manage Batches', school_batches_path(@school), class: 'btn btn-primary' %></p>
        <p><%= link_to 'Manage Courses', school_courses_path(@school), class: 'btn btn-primary' %></p>
        <p><%= link_to 'Manage Students', school_students_path(@school), class: 'btn btn-primary' %></p>
      <% else %>
        <p><%= link_to 'Manage Schools', schools_path, class: 'btn btn-primary' %></p>
        <p><%= link_to 'Manage School Admins', admins_path, class: 'btn btn-primary' %></p>
      <% end %>
      <% elsif current_login.student? %>
        <p><%= link_to 'Request Enrollment', enrollments_school_student_path(@school, @student), class: 'btn btn-primary' %></p>
        <p><%= link_to 'Classmates', classmates_school_student_path(@school, @student), class: 'btn btn-primary' %></p>
      <% end %>
    </div>
  </div>
</div>