config/routes.rb
Rails.application.routes.draw do
  
  resources :exam_evaluations
  devise_for :logins
  
  get 'dashboard/home'

  resources :admins do
    collection do
      get 'home'
    end
  end

  resources :schools do
    resources :batches do
      member do
        get 'add_courses'
        patch 'create_courses'
      end

      resources :enrollments do
        member do
          post 'enrollment_verdict'
        end
      end
    end
    resources :courses
    resources :students do
      member do
        get 'enrollments'
        post 'request_enrollment'
        get 'classmates'
      end

      resources :progress_cards
    end
  end

  
  root "dashboard#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
    enum :admin_type, [:super_admin, :school_admin]
    has_one :login, as: :loginable
    has_one :school
    accepts_nested_attributes_for :login, allow_destroy: true

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/batch.rb
class Batch < ApplicationRecord
    has_many :batches_courses
    has_many :courses, through: :batches_courses
    has_many :progress_cards
    has_many :enrollments
    belongs_to :school, required: false
    accepts_nested_attributes_for :batches_courses, allow_destroy: true

    enum :status, [:inactive, :enrollment_open, :enrollment_closed]

    validates :name, uniqueness: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :status, presence: true


    #This method adds multiple courses to a batch
    def assign_courses(course_ids)
        batches_courses_association_params = course_ids.map {|course_id| {course_id: course_id } }
        batches_courses.create(batches_courses_association_params)
    end
end

app/models/batches_course.rb
class BatchesCourse < ApplicationRecord
    belongs_to :batch
    belongs_to :course

    validates :batch_id, uniqueness: { scope: :course_id }
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :batches_courses
    validates :name, presence: true
    validates :description, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    enum :status, [:requested, :approved, :denied, :completed]
    belongs_to :batch
    belongs_to :student

    validates :batch_id, uniqueness: { scope: :student_id }
end

app/models/exam_evaluation.rb
class ExamEvaluation < ApplicationRecord
    belongs_to :progress_card
    belongs_to :course
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :loginable, polymorphic: true


  #As login table is commom table which is used to log in Admin or Student
  #This method makes sure that if admin? or student? method is called then it responds appropriately
  #User type must be available in the database
  def method_missing(symbol, *args)
    loginable_type_cls = symbol.id2name.gsub('?','').capitalize
    if loginable_type == loginable_type_cls
       true
    elsif Login.distinct.pluck(:loginable_type).include?(loginable_type_cls)
      false
    else
       super(symbol, *args)
    end
  end
end

app/models/progress_card.rb
class ProgressCard < ApplicationRecord
    belongs_to :batch
    belongs_to :student
    has_many :exam_evaluations
    accepts_nested_attributes_for :exam_evaluations

    enum :declaration, [:pass,:fail]
    
    #this method build score card for a student
    #If score is already available for a course then it is considered
    #If score is not available for a course then it is initialized to 0
    def build_score_card(student)
        available_scores = exam_evaluations.pluck(:course_id)
        unavailable_scores = student.current_batch.courses.pluck(:id) - available_scores
        unavailable_scores.each do |una_score|
          exam_evaluations.build(marks: 0, course_id: una_score)
        end
    end
end

app/models/school.rb
class School < ApplicationRecord
    belongs_to :admin, required: false
    has_many :courses
    has_many :students
    has_many :batches

    validates :name, uniqueness: {scope: :email}
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :school
    belongs_to :batch, optional: true
    has_one :login, as: :loginable
    has_many :enrollments
    has_many :progress_cards
    accepts_nested_attributes_for :login, allow_destroy: true

    validates :first_name, presence: true
    validates :middle_name, presence: true
    validates :last_name, presence: true
    validates :date_of_birth, presence: true
    validates :gender, presence: true

    validate :student_age

    enum :gender, ['Female', 'Male']

    def full_name
        "#{first_name} #{middle_name} #{last_name}"
    end

    def enrollment_request_status(batch_id)
        enrollments.find_by(batch_id: batch_id).try(:status)
    end

    def enrollment_requested?(course_id)
        enrollments.exists?(course_id: course_id)
    end

    def current_batch
        enrollments.find_by(status: Enrollment.statuses[:approved]).try :batch
    end

    def classmates
        Student.where(id: Enrollment.where(batch_id: current_batch.id).where.not(student_id: id).pluck(:student_id)) if current_batch
    end

    private

    #Student should be atleast 3 years old
    def student_age
        if date_of_birth && ((Date.today - date_of_birth) < 1095)
            errors.add(:base, 'Student must be atleast 3 Years old')
        end
    end
    
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: %i[ show edit update destroy ]

  # GET /admins or /admins.json
  def index
    @admins = Admin.where(admin_type: Admin.admin_types[:school_admin])
    authorize @admins
  end

  # GET /admins/1 or /admins/1.json
  def show
    authorize @admin
  end

  # GET /admins/new
  def new
    @admin = Admin.new
    authorize @admin
    @admin.build_login
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins or /admins.json
  def create
    @admin = Admin.new(admin_params)
    @admin.admin_type = Admin.admin_types['school_admin']
    
    authorize @admin

    respond_to do |format|
      if @admin.save
        format.html { redirect_to admin_url(@admin), notice: "Admin was successfully created." }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1 or /admins/1.json
  def update
    authorize @admin
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to admin_url(@admin), notice: "Admin was successfully updated." }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1 or /admins/1.json
  def destroy
    authorize @admin
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to admins_url, notice: "Admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_params
      params.require(:admin).permit(:first_name, :last_name, login_attributes: [:email, :password, :password_confirmation])
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
    def batch_select_options
        Batch.statuses.keys
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
    def school_admin_select
        Admin.where(admin_type: 1).map {|admin| [admin.full_name, admin.id] }
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/_admin.html.erb
<td><%= admin.first_name %></td>
<td><%= admin.last_name %></td>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <%= form.fields_for :login do |login| %>
    <div class="form-group">
      <%= login.label :email, style: "display: block" %>
      <%= login.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= login.label :password, style: "display: block" %>
      <%= login.password_field :password, class: 'form-control' %>
    </div>

   <div class="form-group">
      <%= login.label :password_confirmation, style: "display: block" %>
      <%= login.password_field :password_confirmation , class: 'form-control'%>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>

<table class="table" id=schools>
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr id="<%= dom_id admin %>">
         <%= render admin %>
        <td><%= link_to "Edit", edit_admin_path(admin) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New admin", new_admin_path, class: 'btn btn-primary' %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<div class="row">
  <div class="mx-auto col-10 col-md-8 col-lg-6">
    <%= render "form", admin: @admin %>
  </div>
</div>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin %>

<div>
  <%= link_to "Edit this admin", edit_admin_path(@admin) %> |
  <%= link_to "Back to admins", admins_path %>

  <%= button_to "Destroy this admin", @admin, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning Management System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">LMS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", dashboard_home_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_login_session_path, data: { "turbo-method": :delete }, class: 'nav-link' %>
          </li>
          </ul>
        </div>
     </nav>
    <p><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>