config/routes.rb
Rails.application.routes.draw do
  
  resources :exam_evaluations
  devise_for :logins
  
  get 'dashboard/home'

  resources :admins do
    collection do
      get 'home'
    end
  end

  resources :schools do
    resources :batches do
      member do
        get 'add_courses'
        patch 'create_courses'
      end

      resources :enrollments do
        member do
          post 'enrollment_verdict'
        end
      end
    end
    resources :courses
    resources :students do
      member do
        get 'enrollments'
        post 'request_enrollment'
        get 'classmates'
      end

      resources :progress_cards
    end
  end

  
  root "dashboard#home"
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :school
    belongs_to :batch, optional: true
    has_one :login, as: :loginable
    has_many :enrollments
    has_many :progress_cards
    accepts_nested_attributes_for :login, allow_destroy: true

    validates :first_name, presence: true
    validates :middle_name, presence: true
    validates :last_name, presence: true
    validates :date_of_birth, presence: true
    validates :gender, presence: true

    validate :student_age

    enum :gender, ['Female', 'Male']

    def full_name
        "#{first_name} #{middle_name} #{last_name}"
    end

    def enrollment_request_status(batch_id)
        enrollments.find_by(batch_id: batch_id).try(:status)
    end

    def enrollment_requested?(course_id)
        enrollments.exists?(course_id: course_id)
    end

    def current_batch
        enrollments.find_by(status: Enrollment.statuses[:approved]).try :batch
    end

    def classmates
        Student.where(id: Enrollment.where(batch_id: current_batch.id).where.not(student_id: id).pluck(:student_id)) if current_batch
    end

    private

    #Student should be atleast 3 years old
    def student_age
        if date_of_birth && ((Date.today - date_of_birth) < 1095)
            errors.add(:base, 'Student must be atleast 3 Years old')
        end
    end
    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include SetContext
  before_action :set_student, only: %i[ show edit update destroy enrollments request_enrollment classmates]
  before_action :set_school, only: %i[ index new create show edit update destroy enrollments request_enrollment classmates]

  # GET /students or /students.json
  def index
    @students = @school.students
    authorize @students
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.build_login
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    @student.school_id = @school.id

    respond_to do |format|
      if @student.save
        format.html { redirect_to school_student_url(@school, @student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: school_student_url(@school, @student) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to school_student_url(@school, @student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to school_students_url(@school), notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def enrollments
    @batches = @school.batches.includes(:enrollments)
  end

  def request_enrollment
    @enrollment_request = @student.enrollments.new({batch_id: enrollment_params[:batch_id], status: Enrollment.statuses[:requested]})

    respond_to do |format|
      if @enrollment_request.save
        format.html { redirect_to enrollments_school_student_path(@school, @student), notice: "Enrollment request succesfully created" }
        format.json { render :request_enrollment, status: :created, message: "Enrollment request succesfully created" }
      else
        format.html { redirect_to enrollments_school_student_path(@school, @student), notice: @enrollment_request.errors.full_messages.join }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def classmates
    @classmates = @student.classmates
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
      authorize @student
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :middle_name, :last_name, :date_of_birth, :gender, login_attributes: [:email, :password, :password_confirmation])
    end

    def enrollment_params
      params.permit(:batch_id, :school_id, :student_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, url: form_path) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :middle_name, style: "display: block" %>
    <%= form.text_field :middle_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.select :gender, Student.genders.keys %>
  </div>

  <%= form.fields_for :login do |login| %>
    <div>
      <%= login.label :email, style: "display: block" %>
      <%= login.text_field :email %>
    </div>

    <div>
      <%= login.label :password, style: "display: block" %>
      <%= login.password_field :password %>
    </div>

    <div>
      <%= login.label :password_confirmation, style: "display: block" %>
      <%= login.password_field :password_confirmation %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<td><%= student.first_name %></td>
<td><%= student.middle_name %></td>
<td><%= student.last_name %></td>
<td><%= student.date_of_birth %></td>
<td><%= student.gender %></td>

app/views/students/classmates.html.erb
<h1>Classmates</h1>

<% if @classmates %>
<table>
  <thead>
  <tr>
    <td>Classmate Name</td>
    <td>Action</td>
  </tr>
  </thead>
  <tbody>
    <% @classmates.each do |student| %>
    <tr>
        <td><%= student.full_name %></td>
        <td><%= link_to "Progress Card", school_student_progress_cards_path(@school,@student) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  You are not enrolled in any batch
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student, form_path: school_student_path(@school,@student) %>

<br>

<div>
  <%= link_to "Show this student", school_student_path(@school, @student) %> |
  <%= link_to "Back to students", school_students_path(@school) %>
</div>

app/views/students/enrollments.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <div class="row justify-content-center">
    <h3>Available Batches</h3>
  </div>
</div>

<table class="table" id=enrollments>
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Enrollment Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @batches.each do |batch| %>
      <tr id="<%= dom_id batch %>">
        <td><%= batch.name %></td>
        <td><%= @student.enrollment_request_status(batch.id).to_s.humanize %></td>
        <td>
          <% unless @student.enrollment_request_status(batch.id) %>
            <%= button_to "Request Enrollment",  request_enrollment_school_student_path(school_id: @school.id, batch_id: batch.id), class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <div class="row justify-content-center">
    <h3>Students</h3>
  </div>
</div>

<table class="table" id=students>
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Middle Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Date Of Birth</th>
      <th scope="col">Gender</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
   <% @students.each do |student| %>
      <tr id="<%= dom_id student %>">
        <%= render student %>
        <td><%= link_to "Edit", edit_school_student_path(@school, student) %></td>
        <td><%= link_to "Manage Progress Cards", school_student_progress_cards_path(@school,student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "New student", new_school_student_path(@school), class: 'btn btn-primary' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student, form_path: school_students_path(@school) %>

<br>

<div>
  <%= link_to "Back to students", school_students_path(@school) %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_school_student_path(@school, @student) %> |
  <%= link_to "Back to students", school_students_path(@school) %>

  <%= button_to "Destroy this student", school_student_path(@school, @student), method: :delete %>
</div>