config/routes.rb
Rails.application.routes.draw do
  
  resources :exam_evaluations
  devise_for :logins
  
  get 'dashboard/home'

  resources :admins do
    collection do
      get 'home'
    end
  end

  resources :schools do
    resources :batches do
      member do
        get 'add_courses'
        patch 'create_courses'
      end

      resources :enrollments do
        member do
          post 'enrollment_verdict'
        end
      end
    end
    resources :courses
    resources :students do
      member do
        get 'enrollments'
        post 'request_enrollment'
        get 'classmates'
      end

      resources :progress_cards
    end
  end

  
  root "dashboard#home"
end

app/models/batch.rb
class Batch < ApplicationRecord
    has_many :batches_courses
    has_many :courses, through: :batches_courses
    has_many :progress_cards
    has_many :enrollments
    belongs_to :school, required: false
    accepts_nested_attributes_for :batches_courses, allow_destroy: true

    enum :status, [:inactive, :enrollment_open, :enrollment_closed]

    validates :name, uniqueness: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :status, presence: true


    #This method adds multiple courses to a batch
    def assign_courses(course_ids)
        batches_courses_association_params = course_ids.map {|course_id| {course_id: course_id } }
        batches_courses.create(batches_courses_association_params)
    end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  include SetContext
  before_action :set_batch, only: %i[ show edit update destroy add_courses create_courses]
  before_action :set_school, only: %i[ index new create show edit update destroy add_courses create_courses]

  # GET /batches or /batches.json
  def index
    @batches = Batch.where(school_id: current_login.loginable.school.try(:id))
    authorize @batches
  end

  # GET /batches/1 or /batches/1.json
  def show
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches or /batches.json
  def create
    @batch = Batch.new(batch_params)
    @batch.school_id = @school.id

    respond_to do |format|
      if @batch.save
        format.html { redirect_to school_batch_url(@school,@batch), notice: "Batch was successfully created." }
        format.json { render :show, status: :created, location: school_batch_url(@school,@batch) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1 or /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to batch_url(@batch), notice: "Batch was successfully updated." }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1 or /batches/1.json
  def destroy
    @batch.destroy

    respond_to do |format|
      format.html { redirect_to school_batches_url(@school), notice: "Batch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_courses
    @courses =  @school.courses
  end

  def create_courses
    respond_to do |format|
      if  @batches_courses = @batch.assign_courses(batches_courses_params[:course_id])
        format.html { redirect_to school_courses_url(school_id: @school.id,batch_id: @batch.id), notice: "Courses assigned successfully." }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_batch
      @batch = Batch.find(params[:id])
      authorize @batch
    end

    def batch_params
      params.require(:batch).permit(:name, :start_date, :end_date, :status)
    end

    def batches_courses_params
      params.require(:batch).permit(course_id: [])
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
    def batch_select_options
        Batch.statuses.keys
    end
end

app/views/batches/_batch.html.erb
<td><%= batch.name %></td>
<td><%= batch.start_date %></td>
<td><%= batch.end_date %></td>

app/views/batches/_form.html.erb
<%= form_with(model: batch, url: school_batches_path(@school)) do |form| %>
  <% if batch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
        <% batch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, batch_select_options %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/batches/add_courses.html.erb
<%= form_with(model: @batch, url: create_courses_school_batch_path(@school, @batch)) do |form| %>
  <% if @batch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
        <% @batch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>Select Courses</p>

  <% @courses.each do |course| %>
    <div>
        <%= label_tag course.name %>
        <%= form.check_box :course_id, {multiple: true, style: "display: block"}, course.id %>
    </div>
  <% end %>

  <div>
    <%= form.submit "Add Courses" %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing batch</h1>

<%= render "form", batch: @batch %>

<br>

<div>
  <%= link_to "Back to batches", school_batches_path %>
</div>

app/views/batches/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <div class="row justify-content-center">
    <h3>Batches</h3>
  </div>
</div>

<table class="table" id=batches>
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Actions</th>

    </tr>
  </thead>
  <tbody>
    <% @batches.each do |batch| %>
      <tr id="<%= dom_id batch %>">
        <%= render batch %>
        <td><%= link_to "Edit", edit_school_batch_path(@school, batch) %></td>
        <td><%= link_to "Manage Course", school_courses_path(school_id: @school.id,batch_id: batch.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New batch", new_school_batch_path(@school), class: 'btn btn-primary' %>

app/views/batches/new.html.erb
<h1>New batch</h1>

<%= render "form", batch: @batch %>

<br>

<div>
  <%= link_to "Back to batches", school_batches_path(@school) %>
</div>

app/views/batches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @batch %>

<div>
  <%= link_to "Edit this batch", edit_school_batch_path(@school, @batch) %> |
  <%= link_to "Back to batches", school_batches_path(@school) %>

  <%= button_to "Destroy this batch", school_batch_path(@school,@batch), method: :delete %>
</div>